#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0xC304C4A3104005E9 (kamil.konieczny@linux.intel.com)
#
Name     : igt-gpu-tools
Version  : 1.29
Release  : 20
URL      : https://www.x.org/releases/individual/app/igt-gpu-tools-1.29.tar.xz
Source0  : https://www.x.org/releases/individual/app/igt-gpu-tools-1.29.tar.xz
Source1  : https://www.x.org/releases/individual/app/igt-gpu-tools-1.29.tar.xz.sig
Source2  : C304C4A3104005E9.pkey
Summary  : An assembler compiler for the Intel 965+ Chipset
Group    : Development/Tools
License  : MIT
Requires: igt-gpu-tools-bin = %{version}-%{release}
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-lib = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : cairo-dev
BuildRequires : flex
BuildRequires : gnupg
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdw)
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(xv)
BuildRequires : procps-ng-dev
BuildRequires : pypi-docutils
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
IGT GPU Tools
=============
Description
-----------
IGT GPU Tools is a collection of tools for development and testing of the DRM
drivers. There are many macro-level test suites that get used against the
drivers, including xtest, rendercheck, piglit, and oglconform, but failures from
those can be difficult to track down to kernel changes, and many require
complicated build procedures or specific testing environments to get useful
results. Therefore, IGT GPU Tools includes low-level tools and tests
specifically for development and testing of the DRM Drivers.

%package bin
Summary: bin components for the igt-gpu-tools package.
Group: Binaries
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}

%description bin
bin components for the igt-gpu-tools package.


%package data
Summary: data components for the igt-gpu-tools package.
Group: Data

%description data
data components for the igt-gpu-tools package.


%package dev
Summary: dev components for the igt-gpu-tools package.
Group: Development
Requires: igt-gpu-tools-lib = %{version}-%{release}
Requires: igt-gpu-tools-bin = %{version}-%{release}
Requires: igt-gpu-tools-data = %{version}-%{release}
Provides: igt-gpu-tools-devel = %{version}-%{release}
Requires: igt-gpu-tools = %{version}-%{release}

%description dev
dev components for the igt-gpu-tools package.


%package lib
Summary: lib components for the igt-gpu-tools package.
Group: Libraries
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}

%description lib
lib components for the igt-gpu-tools package.


%package libexec
Summary: libexec components for the igt-gpu-tools package.
Group: Default
Requires: igt-gpu-tools-license = %{version}-%{release}

%description libexec
libexec components for the igt-gpu-tools package.


%package license
Summary: license components for the igt-gpu-tools package.
Group: Default

%description license
license components for the igt-gpu-tools package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) C304C4A3104005E9' gpg.status
%setup -q -n igt-gpu-tools-1.29
cd %{_builddir}/igt-gpu-tools-1.29

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725468064
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Doverlay=disabled \
-Dchamelium=disabled \
-Dman=disabled \
-Ddocs=disabled \
-Dtests=enabled \
-Dlibunwind=enabled \
-Dvalgrind=enabled \
-Doping=disabled  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/igt-gpu-tools
cp %{_builddir}/igt-gpu-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/igt-gpu-tools/b7c2a42073c539ec92c45935081d17641175d61f || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/amd_hdmi_compliance
/usr/bin/code_cov_capture
/usr/bin/code_cov_gather_on_build
/usr/bin/code_cov_gather_on_test
/usr/bin/code_cov_gen_report
/usr/bin/code_cov_parse_info
/usr/bin/dpcd_reg
/usr/bin/gputop
/usr/bin/i915-perf-configs
/usr/bin/i915-perf-control
/usr/bin/i915-perf-reader
/usr/bin/i915-perf-recorder
/usr/bin/igt_comms_decoder
/usr/bin/igt_results
/usr/bin/igt_resume
/usr/bin/igt_runner
/usr/bin/igt_stats
/usr/bin/intel-gen4asm
/usr/bin/intel-gen4disasm
/usr/bin/intel-gfx-fw-info
/usr/bin/intel_audio_dump
/usr/bin/intel_backlight
/usr/bin/intel_bios_dumper
/usr/bin/intel_display_crc
/usr/bin/intel_display_poller
/usr/bin/intel_dp_compliance
/usr/bin/intel_dump_decode
/usr/bin/intel_error_decode
/usr/bin/intel_firmware_decode
/usr/bin/intel_forcewaked
/usr/bin/intel_framebuffer_dump
/usr/bin/intel_gem_info
/usr/bin/intel_gpu_abrt
/usr/bin/intel_gpu_frequency
/usr/bin/intel_gpu_time
/usr/bin/intel_gpu_top
/usr/bin/intel_gtt
/usr/bin/intel_guc_logger
/usr/bin/intel_gvtg_test
/usr/bin/intel_infoframes
/usr/bin/intel_l3_parity
/usr/bin/intel_lid
/usr/bin/intel_opregion_decode
/usr/bin/intel_panel_fitter
/usr/bin/intel_perf_counters
/usr/bin/intel_pm_rpm
/usr/bin/intel_reg
/usr/bin/intel_reg_checker
/usr/bin/intel_residency
/usr/bin/intel_stepping
/usr/bin/intel_tiling_detect
/usr/bin/intel_vbt_decode
/usr/bin/intel_watermark
/usr/bin/lsgpu
/usr/bin/msm_dp_compliance
/usr/bin/xe-perf-configs
/usr/bin/xe-perf-control
/usr/bin/xe-perf-reader
/usr/bin/xe-perf-recorder

%files data
%defattr(-,root,root,-)
/usr/share/igt-gpu-tools/1080p-left.png
/usr/share/igt-gpu-tools/1080p-right.png
/usr/share/igt-gpu-tools/README
/usr/share/igt-gpu-tools/blacklist-pre-merge.txt
/usr/share/igt-gpu-tools/blacklist.txt
/usr/share/igt-gpu-tools/chamelium-only.testlist
/usr/share/igt-gpu-tools/fast-feedback-chamelium-only.testlist
/usr/share/igt-gpu-tools/fast-feedback.testlist
/usr/share/igt-gpu-tools/meta.testlist
/usr/share/igt-gpu-tools/pass.png
/usr/share/igt-gpu-tools/registers/audio_config_haswell_plus.txt
/usr/share/igt-gpu-tools/registers/audio_debug_haswell_plus.txt
/usr/share/igt-gpu-tools/registers/base_interrupt.txt
/usr/share/igt-gpu-tools/registers/base_other.txt
/usr/share/igt-gpu-tools/registers/base_power.txt
/usr/share/igt-gpu-tools/registers/base_rings.txt
/usr/share/igt-gpu-tools/registers/broadwell
/usr/share/igt-gpu-tools/registers/cherryview
/usr/share/igt-gpu-tools/registers/chv_display_base.txt
/usr/share/igt-gpu-tools/registers/chv_dpio_phy_x1.txt
/usr/share/igt-gpu-tools/registers/chv_dpio_phy_x2.txt
/usr/share/igt-gpu-tools/registers/chv_pipe_b_extra.txt
/usr/share/igt-gpu-tools/registers/chv_pipe_c.txt
/usr/share/igt-gpu-tools/registers/common_display.txt
/usr/share/igt-gpu-tools/registers/gen6_other.txt
/usr/share/igt-gpu-tools/registers/gen7_other.txt
/usr/share/igt-gpu-tools/registers/gen8_interrupt.txt
/usr/share/igt-gpu-tools/registers/gen8_other.txt
/usr/share/igt-gpu-tools/registers/haswell
/usr/share/igt-gpu-tools/registers/haswell_other.txt
/usr/share/igt-gpu-tools/registers/icelake
/usr/share/igt-gpu-tools/registers/icl_delta.txt
/usr/share/igt-gpu-tools/registers/ivybridge
/usr/share/igt-gpu-tools/registers/kabylake
/usr/share/igt-gpu-tools/registers/sandybridge
/usr/share/igt-gpu-tools/registers/skl_display.txt
/usr/share/igt-gpu-tools/registers/skl_powerwells.txt
/usr/share/igt-gpu-tools/registers/skylake
/usr/share/igt-gpu-tools/registers/tigerlake
/usr/share/igt-gpu-tools/registers/tigerlake_delta.txt
/usr/share/igt-gpu-tools/registers/valleyview
/usr/share/igt-gpu-tools/registers/vlv_cck.txt
/usr/share/igt-gpu-tools/registers/vlv_display_base.txt
/usr/share/igt-gpu-tools/registers/vlv_dpio_phy.txt
/usr/share/igt-gpu-tools/registers/vlv_dsi.txt
/usr/share/igt-gpu-tools/registers/vlv_flisdsi.txt
/usr/share/igt-gpu-tools/registers/vlv_pipe_a.txt
/usr/share/igt-gpu-tools/registers/vlv_pipe_b.txt
/usr/share/igt-gpu-tools/registers/vlv_power.txt
/usr/share/igt-gpu-tools/xe-fast-feedback-chamelium-only.testlist
/usr/share/igt-gpu-tools/xe-fast-feedback.testlist
/usr/share/igt-gpu-tools/xe-sriov-vf.blocklist.txt
/usr/share/igt-gpu-tools/xe.blocklist.txt

%files dev
%defattr(-,root,root,-)
/usr/include/i915-perf/igt_list.h
/usr/include/i915-perf/intel_chipset.h
/usr/include/i915-perf/perf.h
/usr/include/i915-perf/perf_data.h
/usr/include/i915-perf/perf_data_reader.h
/usr/include/xe-oa/igt_list.h
/usr/include/xe-oa/intel_chipset.h
/usr/include/xe-oa/xe_oa.h
/usr/include/xe-oa/xe_oa_data.h
/usr/include/xe-oa/xe_oa_data_reader.h
/usr/lib64/libi915_perf.so
/usr/lib64/libigt.so
/usr/lib64/libxe_oa.so
/usr/lib64/pkgconfig/i915-perf.pc
/usr/lib64/pkgconfig/intel-gen4asm.pc
/usr/lib64/pkgconfig/xe-oa.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libi915_perf.so.1.5
/usr/lib64/libigt.so.0
/usr/lib64/libxe_oa.so.1.5

%files libexec
%defattr(-,root,root,-)
/usr/libexec/igt-gpu-tools/amdgpu/amd_abm
/usr/libexec/igt-gpu-tools/amdgpu/amd_assr
/usr/libexec/igt-gpu-tools/amdgpu/amd_basic
/usr/libexec/igt-gpu-tools/amdgpu/amd_bo
/usr/libexec/igt-gpu-tools/amdgpu/amd_bypass
/usr/libexec/igt-gpu-tools/amdgpu/amd_color
/usr/libexec/igt-gpu-tools/amdgpu/amd_cp_dma_misc
/usr/libexec/igt-gpu-tools/amdgpu/amd_cs_nop
/usr/libexec/igt-gpu-tools/amdgpu/amd_deadlock
/usr/libexec/igt-gpu-tools/amdgpu/amd_dispatch
/usr/libexec/igt-gpu-tools/amdgpu/amd_dp_dsc
/usr/libexec/igt-gpu-tools/amdgpu/amd_freesync_video_mode
/usr/libexec/igt-gpu-tools/amdgpu/amd_fuzzing
/usr/libexec/igt-gpu-tools/amdgpu/amd_gang_cs
/usr/libexec/igt-gpu-tools/amdgpu/amd_hotplug
/usr/libexec/igt-gpu-tools/amdgpu/amd_ilr
/usr/libexec/igt-gpu-tools/amdgpu/amd_info
/usr/libexec/igt-gpu-tools/amdgpu/amd_jpeg_dec
/usr/libexec/igt-gpu-tools/amdgpu/amd_link_settings
/usr/libexec/igt-gpu-tools/amdgpu/amd_mall
/usr/libexec/igt-gpu-tools/amdgpu/amd_max_bpc
/usr/libexec/igt-gpu-tools/amdgpu/amd_mem_leak
/usr/libexec/igt-gpu-tools/amdgpu/amd_mode_switch
/usr/libexec/igt-gpu-tools/amdgpu/amd_module_load
/usr/libexec/igt-gpu-tools/amdgpu/amd_multidisplay_modeset
/usr/libexec/igt-gpu-tools/amdgpu/amd_odm
/usr/libexec/igt-gpu-tools/amdgpu/amd_pci_unplug
/usr/libexec/igt-gpu-tools/amdgpu/amd_plane
/usr/libexec/igt-gpu-tools/amdgpu/amd_prime
/usr/libexec/igt-gpu-tools/amdgpu/amd_psr
/usr/libexec/igt-gpu-tools/amdgpu/amd_pstate
/usr/libexec/igt-gpu-tools/amdgpu/amd_queue_reset
/usr/libexec/igt-gpu-tools/amdgpu/amd_ras
/usr/libexec/igt-gpu-tools/amdgpu/amd_replay
/usr/libexec/igt-gpu-tools/amdgpu/amd_security
/usr/libexec/igt-gpu-tools/amdgpu/amd_subvp
/usr/libexec/igt-gpu-tools/amdgpu/amd_syncobj
/usr/libexec/igt-gpu-tools/amdgpu/amd_uvd_dec
/usr/libexec/igt-gpu-tools/amdgpu/amd_uvd_enc
/usr/libexec/igt-gpu-tools/amdgpu/amd_vce_enc
/usr/libexec/igt-gpu-tools/amdgpu/amd_vcn
/usr/libexec/igt-gpu-tools/amdgpu/amd_vm
/usr/libexec/igt-gpu-tools/amdgpu/amd_vpe
/usr/libexec/igt-gpu-tools/amdgpu/amd_vrr_range
/usr/libexec/igt-gpu-tools/api_intel_allocator
/usr/libexec/igt-gpu-tools/api_intel_bb
/usr/libexec/igt-gpu-tools/benchmarks/gem_blt
/usr/libexec/igt-gpu-tools/benchmarks/gem_busy
/usr/libexec/igt-gpu-tools/benchmarks/gem_create
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_ctx
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_fault
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_nop
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_reloc
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_trace
/usr/libexec/igt-gpu-tools/benchmarks/gem_latency
/usr/libexec/igt-gpu-tools/benchmarks/gem_prw
/usr/libexec/igt-gpu-tools/benchmarks/gem_set_domain
/usr/libexec/igt-gpu-tools/benchmarks/gem_syslatency
/usr/libexec/igt-gpu-tools/benchmarks/gem_userptr_benchmark
/usr/libexec/igt-gpu-tools/benchmarks/gem_wsim
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large_gtt
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large_map
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_small
/usr/libexec/igt-gpu-tools/benchmarks/kms_fb_stress
/usr/libexec/igt-gpu-tools/benchmarks/kms_vblank
/usr/libexec/igt-gpu-tools/benchmarks/libgem_exec_tracer.so
/usr/libexec/igt-gpu-tools/benchmarks/prime_lookup
/usr/libexec/igt-gpu-tools/benchmarks/vgem_mmap
/usr/libexec/igt-gpu-tools/core_auth
/usr/libexec/igt-gpu-tools/core_getclient
/usr/libexec/igt-gpu-tools/core_getstats
/usr/libexec/igt-gpu-tools/core_getversion
/usr/libexec/igt-gpu-tools/core_hotunplug
/usr/libexec/igt-gpu-tools/core_setmaster
/usr/libexec/igt-gpu-tools/core_setmaster_vs_auth
/usr/libexec/igt-gpu-tools/debugfs_test
/usr/libexec/igt-gpu-tools/device_reset
/usr/libexec/igt-gpu-tools/dmabuf
/usr/libexec/igt-gpu-tools/dmabuf_sync_file
/usr/libexec/igt-gpu-tools/drm_buddy
/usr/libexec/igt-gpu-tools/drm_fdinfo
/usr/libexec/igt-gpu-tools/drm_mm
/usr/libexec/igt-gpu-tools/drm_read
/usr/libexec/igt-gpu-tools/dumb_buffer
/usr/libexec/igt-gpu-tools/fbdev
/usr/libexec/igt-gpu-tools/gem_bad_reloc
/usr/libexec/igt-gpu-tools/gem_barrier_race
/usr/libexec/igt-gpu-tools/gem_basic
/usr/libexec/igt-gpu-tools/gem_blits
/usr/libexec/igt-gpu-tools/gem_busy
/usr/libexec/igt-gpu-tools/gem_caching
/usr/libexec/igt-gpu-tools/gem_ccs
/usr/libexec/igt-gpu-tools/gem_close
/usr/libexec/igt-gpu-tools/gem_close_race
/usr/libexec/igt-gpu-tools/gem_compute
/usr/libexec/igt-gpu-tools/gem_concurrent_all
/usr/libexec/igt-gpu-tools/gem_concurrent_blit
/usr/libexec/igt-gpu-tools/gem_create
/usr/libexec/igt-gpu-tools/gem_cs_tlb
/usr/libexec/igt-gpu-tools/gem_ctx_bad_destroy
/usr/libexec/igt-gpu-tools/gem_ctx_create
/usr/libexec/igt-gpu-tools/gem_ctx_engines
/usr/libexec/igt-gpu-tools/gem_ctx_exec
/usr/libexec/igt-gpu-tools/gem_ctx_freq
/usr/libexec/igt-gpu-tools/gem_ctx_isolation
/usr/libexec/igt-gpu-tools/gem_ctx_param
/usr/libexec/igt-gpu-tools/gem_ctx_persistence
/usr/libexec/igt-gpu-tools/gem_ctx_shared
/usr/libexec/igt-gpu-tools/gem_ctx_sseu
/usr/libexec/igt-gpu-tools/gem_ctx_switch
/usr/libexec/igt-gpu-tools/gem_eio
/usr/libexec/igt-gpu-tools/gem_evict_alignment
/usr/libexec/igt-gpu-tools/gem_evict_everything
/usr/libexec/igt-gpu-tools/gem_exec_alignment
/usr/libexec/igt-gpu-tools/gem_exec_async
/usr/libexec/igt-gpu-tools/gem_exec_await
/usr/libexec/igt-gpu-tools/gem_exec_balancer
/usr/libexec/igt-gpu-tools/gem_exec_basic
/usr/libexec/igt-gpu-tools/gem_exec_big
/usr/libexec/igt-gpu-tools/gem_exec_capture
/usr/libexec/igt-gpu-tools/gem_exec_create
/usr/libexec/igt-gpu-tools/gem_exec_endless
/usr/libexec/igt-gpu-tools/gem_exec_fair
/usr/libexec/igt-gpu-tools/gem_exec_fence
/usr/libexec/igt-gpu-tools/gem_exec_flush
/usr/libexec/igt-gpu-tools/gem_exec_gttfill
/usr/libexec/igt-gpu-tools/gem_exec_latency
/usr/libexec/igt-gpu-tools/gem_exec_lut_handle
/usr/libexec/igt-gpu-tools/gem_exec_nop
/usr/libexec/igt-gpu-tools/gem_exec_parallel
/usr/libexec/igt-gpu-tools/gem_exec_params
/usr/libexec/igt-gpu-tools/gem_exec_reloc
/usr/libexec/igt-gpu-tools/gem_exec_schedule
/usr/libexec/igt-gpu-tools/gem_exec_store
/usr/libexec/igt-gpu-tools/gem_exec_suspend
/usr/libexec/igt-gpu-tools/gem_exec_whisper
/usr/libexec/igt-gpu-tools/gem_exercise_blt
/usr/libexec/igt-gpu-tools/gem_fd_exhaustion
/usr/libexec/igt-gpu-tools/gem_fence_thrash
/usr/libexec/igt-gpu-tools/gem_fence_upload
/usr/libexec/igt-gpu-tools/gem_fenced_exec_thrash
/usr/libexec/igt-gpu-tools/gem_flink_basic
/usr/libexec/igt-gpu-tools/gem_flink_race
/usr/libexec/igt-gpu-tools/gem_gpgpu_fill
/usr/libexec/igt-gpu-tools/gem_gtt_cpu_tlb
/usr/libexec/igt-gpu-tools/gem_gtt_hog
/usr/libexec/igt-gpu-tools/gem_gtt_speed
/usr/libexec/igt-gpu-tools/gem_huc_copy
/usr/libexec/igt-gpu-tools/gem_linear_blits
/usr/libexec/igt-gpu-tools/gem_lmem_evict
/usr/libexec/igt-gpu-tools/gem_lmem_swapping
/usr/libexec/igt-gpu-tools/gem_lut_handle
/usr/libexec/igt-gpu-tools/gem_madvise
/usr/libexec/igt-gpu-tools/gem_media_fill
/usr/libexec/igt-gpu-tools/gem_media_vme
/usr/libexec/igt-gpu-tools/gem_mmap
/usr/libexec/igt-gpu-tools/gem_mmap_gtt
/usr/libexec/igt-gpu-tools/gem_mmap_offset
/usr/libexec/igt-gpu-tools/gem_mmap_wc
/usr/libexec/igt-gpu-tools/gem_partial_pwrite_pread
/usr/libexec/igt-gpu-tools/gem_pipe_control_store_loop
/usr/libexec/igt-gpu-tools/gem_ppgtt
/usr/libexec/igt-gpu-tools/gem_pread
/usr/libexec/igt-gpu-tools/gem_pread_after_blit
/usr/libexec/igt-gpu-tools/gem_pwrite
/usr/libexec/igt-gpu-tools/gem_pwrite_snooped
/usr/libexec/igt-gpu-tools/gem_pxp
/usr/libexec/igt-gpu-tools/gem_read_read_speed
/usr/libexec/igt-gpu-tools/gem_readwrite
/usr/libexec/igt-gpu-tools/gem_reg_read
/usr/libexec/igt-gpu-tools/gem_render_copy
/usr/libexec/igt-gpu-tools/gem_render_copy_redux
/usr/libexec/igt-gpu-tools/gem_render_linear_blits
/usr/libexec/igt-gpu-tools/gem_render_tiled_blits
/usr/libexec/igt-gpu-tools/gem_request_retire
/usr/libexec/igt-gpu-tools/gem_reset_stats
/usr/libexec/igt-gpu-tools/gem_ringfill
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_blt
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_gtt
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_pwrite
/usr/libexec/igt-gpu-tools/gem_shrink
/usr/libexec/igt-gpu-tools/gem_softpin
/usr/libexec/igt-gpu-tools/gem_spin_batch
/usr/libexec/igt-gpu-tools/gem_streaming_writes
/usr/libexec/igt-gpu-tools/gem_stress
/usr/libexec/igt-gpu-tools/gem_sync
/usr/libexec/igt-gpu-tools/gem_tiled_blits
/usr/libexec/igt-gpu-tools/gem_tiled_fence_blits
/usr/libexec/igt-gpu-tools/gem_tiled_partial_pwrite_pread
/usr/libexec/igt-gpu-tools/gem_tiled_pread_basic
/usr/libexec/igt-gpu-tools/gem_tiled_pread_pwrite
/usr/libexec/igt-gpu-tools/gem_tiled_swapping
/usr/libexec/igt-gpu-tools/gem_tiled_wb
/usr/libexec/igt-gpu-tools/gem_tiled_wc
/usr/libexec/igt-gpu-tools/gem_tiling_max_stride
/usr/libexec/igt-gpu-tools/gem_unfence_active_buffers
/usr/libexec/igt-gpu-tools/gem_unref_active_buffers
/usr/libexec/igt-gpu-tools/gem_userptr_blits
/usr/libexec/igt-gpu-tools/gem_vm_create
/usr/libexec/igt-gpu-tools/gem_wait
/usr/libexec/igt-gpu-tools/gem_watchdog
/usr/libexec/igt-gpu-tools/gem_workarounds
/usr/libexec/igt-gpu-tools/gen3_mixed_blits
/usr/libexec/igt-gpu-tools/gen3_render_linear_blits
/usr/libexec/igt-gpu-tools/gen3_render_mixed_blits
/usr/libexec/igt-gpu-tools/gen3_render_tiledx_blits
/usr/libexec/igt-gpu-tools/gen3_render_tiledy_blits
/usr/libexec/igt-gpu-tools/gen7_exec_parse
/usr/libexec/igt-gpu-tools/gen9_exec_parse
/usr/libexec/igt-gpu-tools/i915_fb_tiling
/usr/libexec/igt-gpu-tools/i915_getparams_basic
/usr/libexec/igt-gpu-tools/i915_hangman
/usr/libexec/igt-gpu-tools/i915_module_load
/usr/libexec/igt-gpu-tools/i915_pciid
/usr/libexec/igt-gpu-tools/i915_pipe_stress
/usr/libexec/igt-gpu-tools/i915_pm_freq_api
/usr/libexec/igt-gpu-tools/i915_pm_freq_mult
/usr/libexec/igt-gpu-tools/i915_pm_rc6_residency
/usr/libexec/igt-gpu-tools/i915_pm_rpm
/usr/libexec/igt-gpu-tools/i915_pm_rps
/usr/libexec/igt-gpu-tools/i915_pm_sseu
/usr/libexec/igt-gpu-tools/i915_power
/usr/libexec/igt-gpu-tools/i915_query
/usr/libexec/igt-gpu-tools/i915_selftest
/usr/libexec/igt-gpu-tools/i915_suspend
/usr/libexec/igt-gpu-tools/intel-ci-tests/i915/default/bat-chamelium.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/i915/default/bat.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/i915/default/chamelium.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/i915/default/full.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/i915/default/other.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/xe/default/bat-chamelium.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/xe/default/bat.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/xe/default/full.testlist
/usr/libexec/igt-gpu-tools/intel-ci-tests/xe/default/other.testlist
/usr/libexec/igt-gpu-tools/intel_hwmon
/usr/libexec/igt-gpu-tools/kms_3d
/usr/libexec/igt-gpu-tools/kms_addfb_basic
/usr/libexec/igt-gpu-tools/kms_async_flips
/usr/libexec/igt-gpu-tools/kms_atomic
/usr/libexec/igt-gpu-tools/kms_atomic_interruptible
/usr/libexec/igt-gpu-tools/kms_atomic_transition
/usr/libexec/igt-gpu-tools/kms_big_fb
/usr/libexec/igt-gpu-tools/kms_big_joiner
/usr/libexec/igt-gpu-tools/kms_busy
/usr/libexec/igt-gpu-tools/kms_bw
/usr/libexec/igt-gpu-tools/kms_ccs
/usr/libexec/igt-gpu-tools/kms_cdclk
/usr/libexec/igt-gpu-tools/kms_color
/usr/libexec/igt-gpu-tools/kms_concurrent
/usr/libexec/igt-gpu-tools/kms_content_protection
/usr/libexec/igt-gpu-tools/kms_cursor_crc
/usr/libexec/igt-gpu-tools/kms_cursor_edge_walk
/usr/libexec/igt-gpu-tools/kms_cursor_legacy
/usr/libexec/igt-gpu-tools/kms_dirtyfb
/usr/libexec/igt-gpu-tools/kms_display_modes
/usr/libexec/igt-gpu-tools/kms_dither
/usr/libexec/igt-gpu-tools/kms_dp_aux_dev
/usr/libexec/igt-gpu-tools/kms_draw_crc
/usr/libexec/igt-gpu-tools/kms_dsc
/usr/libexec/igt-gpu-tools/kms_fb_coherency
/usr/libexec/igt-gpu-tools/kms_fbcon_fbt
/usr/libexec/igt-gpu-tools/kms_feature_discovery
/usr/libexec/igt-gpu-tools/kms_fence_pin_leak
/usr/libexec/igt-gpu-tools/kms_flip
/usr/libexec/igt-gpu-tools/kms_flip_event_leak
/usr/libexec/igt-gpu-tools/kms_flip_scaled_crc
/usr/libexec/igt-gpu-tools/kms_flip_tiling
/usr/libexec/igt-gpu-tools/kms_force_connector_basic
/usr/libexec/igt-gpu-tools/kms_frontbuffer_tracking
/usr/libexec/igt-gpu-tools/kms_getfb
/usr/libexec/igt-gpu-tools/kms_hdmi_inject
/usr/libexec/igt-gpu-tools/kms_hdr
/usr/libexec/igt-gpu-tools/kms_invalid_mode
/usr/libexec/igt-gpu-tools/kms_lease
/usr/libexec/igt-gpu-tools/kms_legacy_colorkey
/usr/libexec/igt-gpu-tools/kms_mmap_write_crc
/usr/libexec/igt-gpu-tools/kms_multipipe_modeset
/usr/libexec/igt-gpu-tools/kms_panel_fitting
/usr/libexec/igt-gpu-tools/kms_pipe_b_c_ivb
/usr/libexec/igt-gpu-tools/kms_pipe_crc_basic
/usr/libexec/igt-gpu-tools/kms_plane
/usr/libexec/igt-gpu-tools/kms_plane_alpha_blend
/usr/libexec/igt-gpu-tools/kms_plane_cursor
/usr/libexec/igt-gpu-tools/kms_plane_lowres
/usr/libexec/igt-gpu-tools/kms_plane_multiple
/usr/libexec/igt-gpu-tools/kms_plane_scaling
/usr/libexec/igt-gpu-tools/kms_pm_backlight
/usr/libexec/igt-gpu-tools/kms_pm_dc
/usr/libexec/igt-gpu-tools/kms_pm_lpsp
/usr/libexec/igt-gpu-tools/kms_pm_rpm
/usr/libexec/igt-gpu-tools/kms_prime
/usr/libexec/igt-gpu-tools/kms_prop_blob
/usr/libexec/igt-gpu-tools/kms_properties
/usr/libexec/igt-gpu-tools/kms_psr
/usr/libexec/igt-gpu-tools/kms_psr2_sf
/usr/libexec/igt-gpu-tools/kms_psr2_su
/usr/libexec/igt-gpu-tools/kms_psr_stress_test
/usr/libexec/igt-gpu-tools/kms_pwrite_crc
/usr/libexec/igt-gpu-tools/kms_rmfb
/usr/libexec/igt-gpu-tools/kms_rotation_crc
/usr/libexec/igt-gpu-tools/kms_scaling_modes
/usr/libexec/igt-gpu-tools/kms_selftest
/usr/libexec/igt-gpu-tools/kms_sequence
/usr/libexec/igt-gpu-tools/kms_setmode
/usr/libexec/igt-gpu-tools/kms_sysfs_edid_timing
/usr/libexec/igt-gpu-tools/kms_tiled_display
/usr/libexec/igt-gpu-tools/kms_tv_load_detect
/usr/libexec/igt-gpu-tools/kms_universal_plane
/usr/libexec/igt-gpu-tools/kms_vblank
/usr/libexec/igt-gpu-tools/kms_vrr
/usr/libexec/igt-gpu-tools/kms_writeback
/usr/libexec/igt-gpu-tools/meta_test
/usr/libexec/igt-gpu-tools/msm/msm_mapping
/usr/libexec/igt-gpu-tools/msm/msm_recovery
/usr/libexec/igt-gpu-tools/msm/msm_shrink
/usr/libexec/igt-gpu-tools/msm/msm_submit
/usr/libexec/igt-gpu-tools/msm/msm_submitoverhead
/usr/libexec/igt-gpu-tools/nouveau_crc
/usr/libexec/igt-gpu-tools/panfrost/panfrost_gem_new
/usr/libexec/igt-gpu-tools/panfrost/panfrost_get_param
/usr/libexec/igt-gpu-tools/panfrost/panfrost_prime
/usr/libexec/igt-gpu-tools/panfrost/panfrost_submit
/usr/libexec/igt-gpu-tools/perf
/usr/libexec/igt-gpu-tools/perf_pmu
/usr/libexec/igt-gpu-tools/prime_busy
/usr/libexec/igt-gpu-tools/prime_mmap
/usr/libexec/igt-gpu-tools/prime_mmap_coherency
/usr/libexec/igt-gpu-tools/prime_mmap_kms
/usr/libexec/igt-gpu-tools/prime_nv_api
/usr/libexec/igt-gpu-tools/prime_nv_pcopy
/usr/libexec/igt-gpu-tools/prime_nv_test
/usr/libexec/igt-gpu-tools/prime_self_import
/usr/libexec/igt-gpu-tools/prime_udl
/usr/libexec/igt-gpu-tools/prime_vgem
/usr/libexec/igt-gpu-tools/sriov_basic
/usr/libexec/igt-gpu-tools/sw_sync
/usr/libexec/igt-gpu-tools/syncobj_basic
/usr/libexec/igt-gpu-tools/syncobj_eventfd
/usr/libexec/igt-gpu-tools/syncobj_timeline
/usr/libexec/igt-gpu-tools/syncobj_wait
/usr/libexec/igt-gpu-tools/sysfs_defaults
/usr/libexec/igt-gpu-tools/sysfs_heartbeat_interval
/usr/libexec/igt-gpu-tools/sysfs_preempt_timeout
/usr/libexec/igt-gpu-tools/sysfs_timeslice_duration
/usr/libexec/igt-gpu-tools/template
/usr/libexec/igt-gpu-tools/test-list-full.txt
/usr/libexec/igt-gpu-tools/test-list.txt
/usr/libexec/igt-gpu-tools/testdisplay
/usr/libexec/igt-gpu-tools/tools_test
/usr/libexec/igt-gpu-tools/v3d/v3d_create_bo
/usr/libexec/igt-gpu-tools/v3d/v3d_get_bo_offset
/usr/libexec/igt-gpu-tools/v3d/v3d_get_param
/usr/libexec/igt-gpu-tools/v3d/v3d_job_submission
/usr/libexec/igt-gpu-tools/v3d/v3d_mmap
/usr/libexec/igt-gpu-tools/v3d/v3d_perfmon
/usr/libexec/igt-gpu-tools/v3d/v3d_submit_cl
/usr/libexec/igt-gpu-tools/v3d/v3d_submit_csd
/usr/libexec/igt-gpu-tools/v3d/v3d_wait_bo
/usr/libexec/igt-gpu-tools/vc4/vc4_create_bo
/usr/libexec/igt-gpu-tools/vc4/vc4_dmabuf_poll
/usr/libexec/igt-gpu-tools/vc4/vc4_label_bo
/usr/libexec/igt-gpu-tools/vc4/vc4_lookup_fail
/usr/libexec/igt-gpu-tools/vc4/vc4_mmap
/usr/libexec/igt-gpu-tools/vc4/vc4_perfmon
/usr/libexec/igt-gpu-tools/vc4/vc4_purgeable_bo
/usr/libexec/igt-gpu-tools/vc4/vc4_tiling
/usr/libexec/igt-gpu-tools/vc4/vc4_wait_bo
/usr/libexec/igt-gpu-tools/vc4/vc4_wait_seqno
/usr/libexec/igt-gpu-tools/vgem_basic
/usr/libexec/igt-gpu-tools/vgem_slow
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_execution_buffer
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_mob_stress
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_prime
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_ref_count
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_surface_copy
/usr/libexec/igt-gpu-tools/vmwgfx/vmw_tri
/usr/libexec/igt-gpu-tools/xe_ccs
/usr/libexec/igt-gpu-tools/xe_compute
/usr/libexec/igt-gpu-tools/xe_compute_preempt
/usr/libexec/igt-gpu-tools/xe_copy_basic
/usr/libexec/igt-gpu-tools/xe_create
/usr/libexec/igt-gpu-tools/xe_debugfs
/usr/libexec/igt-gpu-tools/xe_dma_buf_sync
/usr/libexec/igt-gpu-tools/xe_drm_fdinfo
/usr/libexec/igt-gpu-tools/xe_evict
/usr/libexec/igt-gpu-tools/xe_evict_ccs
/usr/libexec/igt-gpu-tools/xe_exec_atomic
/usr/libexec/igt-gpu-tools/xe_exec_balancer
/usr/libexec/igt-gpu-tools/xe_exec_basic
/usr/libexec/igt-gpu-tools/xe_exec_compute_mode
/usr/libexec/igt-gpu-tools/xe_exec_fault_mode
/usr/libexec/igt-gpu-tools/xe_exec_mix_modes
/usr/libexec/igt-gpu-tools/xe_exec_queue_property
/usr/libexec/igt-gpu-tools/xe_exec_reset
/usr/libexec/igt-gpu-tools/xe_exec_sip
/usr/libexec/igt-gpu-tools/xe_exec_store
/usr/libexec/igt-gpu-tools/xe_exec_threads
/usr/libexec/igt-gpu-tools/xe_exercise_blt
/usr/libexec/igt-gpu-tools/xe_gpgpu_fill
/usr/libexec/igt-gpu-tools/xe_gt_freq
/usr/libexec/igt-gpu-tools/xe_huc_copy
/usr/libexec/igt-gpu-tools/xe_intel_bb
/usr/libexec/igt-gpu-tools/xe_live_ktest
/usr/libexec/igt-gpu-tools/xe_media_fill
/usr/libexec/igt-gpu-tools/xe_mmap
/usr/libexec/igt-gpu-tools/xe_module_load
/usr/libexec/igt-gpu-tools/xe_noexec_ping_pong
/usr/libexec/igt-gpu-tools/xe_oa
/usr/libexec/igt-gpu-tools/xe_pat
/usr/libexec/igt-gpu-tools/xe_peer2peer
/usr/libexec/igt-gpu-tools/xe_pm
/usr/libexec/igt-gpu-tools/xe_pm_residency
/usr/libexec/igt-gpu-tools/xe_prime_self_import
/usr/libexec/igt-gpu-tools/xe_query
/usr/libexec/igt-gpu-tools/xe_render_copy
/usr/libexec/igt-gpu-tools/xe_spin_batch
/usr/libexec/igt-gpu-tools/xe_sysfs_defaults
/usr/libexec/igt-gpu-tools/xe_sysfs_preempt_timeout
/usr/libexec/igt-gpu-tools/xe_sysfs_scheduler
/usr/libexec/igt-gpu-tools/xe_vm
/usr/libexec/igt-gpu-tools/xe_waitfence
/usr/libexec/igt-gpu-tools/xe_wedged

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/igt-gpu-tools/b7c2a42073c539ec92c45935081d17641175d61f
