#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7370055DB74C2475 (petri.latvala@intel.com)
#
Name     : igt-gpu-tools
Version  : 1.24
Release  : 10
URL      : https://xorg.freedesktop.org/releases/individual/app/igt-gpu-tools-1.24.tar.xz
Source0  : https://xorg.freedesktop.org/releases/individual/app/igt-gpu-tools-1.24.tar.xz
Source1 : https://xorg.freedesktop.org/releases/individual/app/igt-gpu-tools-1.24.tar.xz.sig
Summary  : An assembler compiler for the Intel 965+ Chipset
Group    : Development/Tools
License  : MIT
Requires: igt-gpu-tools-bin = %{version}-%{release}
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-lib = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}
Requires: igt-gpu-tools-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : docutils
BuildRequires : flex
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(gtk-doc)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_amdgpu)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libdrm_nouveau)
BuildRequires : pkgconfig(libdw)
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libprocps)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xv)
Patch1: 0001-Fix-global-symbol-loading-failure-in-resolve-functio.patch

%description
IGT GPU Tools
=============
Description
-----------
IGT GPU Tools is a collection of tools for development and testing of the DRM
drivers. There are many macro-level test suites that get used against the
drivers, including xtest, rendercheck, piglit, and oglconform, but failures from
those can be difficult to track down to kernel changes, and many require
complicated build procedures or specific testing environments to get useful
results. Therefore, IGT GPU Tools includes low-level tools and tests
specifically for development and testing of the DRM Drivers.


%package bin
Summary: bin components for the igt-gpu-tools package.
Group: Binaries
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}

%description bin
bin components for the igt-gpu-tools package.


%package data
Summary: data components for the igt-gpu-tools package.
Group: Data

%description data
data components for the igt-gpu-tools package.


%package dev
Summary: dev components for the igt-gpu-tools package.
Group: Development
Requires: igt-gpu-tools-lib = %{version}-%{release}
Requires: igt-gpu-tools-bin = %{version}-%{release}
Requires: igt-gpu-tools-data = %{version}-%{release}
Provides: igt-gpu-tools-devel = %{version}-%{release}
Requires: igt-gpu-tools = %{version}-%{release}

%description dev
dev components for the igt-gpu-tools package.


%package doc
Summary: doc components for the igt-gpu-tools package.
Group: Documentation
Requires: igt-gpu-tools-man = %{version}-%{release}

%description doc
doc components for the igt-gpu-tools package.


%package lib
Summary: lib components for the igt-gpu-tools package.
Group: Libraries
Requires: igt-gpu-tools-data = %{version}-%{release}
Requires: igt-gpu-tools-libexec = %{version}-%{release}
Requires: igt-gpu-tools-license = %{version}-%{release}

%description lib
lib components for the igt-gpu-tools package.


%package libexec
Summary: libexec components for the igt-gpu-tools package.
Group: Default
Requires: igt-gpu-tools-license = %{version}-%{release}

%description libexec
libexec components for the igt-gpu-tools package.


%package license
Summary: license components for the igt-gpu-tools package.
Group: Default

%description license
license components for the igt-gpu-tools package.


%package man
Summary: man components for the igt-gpu-tools package.
Group: Default

%description man
man components for the igt-gpu-tools package.


%prep
%setup -q -n igt-gpu-tools-1.24
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569966605
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
ninja -v -C builddir test

%install
mkdir -p %{buildroot}/usr/share/package-licenses/igt-gpu-tools
cp COPYING %{buildroot}/usr/share/package-licenses/igt-gpu-tools/COPYING
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dpcd_reg
/usr/bin/igt_results
/usr/bin/igt_resume
/usr/bin/igt_runner
/usr/bin/igt_stats
/usr/bin/intel-gen4asm
/usr/bin/intel-gen4disasm
/usr/bin/intel_aubdump
/usr/bin/intel_audio_dump
/usr/bin/intel_backlight
/usr/bin/intel_bios_dumper
/usr/bin/intel_display_crc
/usr/bin/intel_display_poller
/usr/bin/intel_dp_compliance
/usr/bin/intel_dump_decode
/usr/bin/intel_error_decode
/usr/bin/intel_firmware_decode
/usr/bin/intel_forcewaked
/usr/bin/intel_framebuffer_dump
/usr/bin/intel_gem_info
/usr/bin/intel_gpu_abrt
/usr/bin/intel_gpu_frequency
/usr/bin/intel_gpu_time
/usr/bin/intel_gpu_top
/usr/bin/intel_gtt
/usr/bin/intel_guc_logger
/usr/bin/intel_gvtg_test
/usr/bin/intel_infoframes
/usr/bin/intel_l3_parity
/usr/bin/intel_lid
/usr/bin/intel_opregion_decode
/usr/bin/intel_panel_fitter
/usr/bin/intel_perf_counters
/usr/bin/intel_reg
/usr/bin/intel_reg_checker
/usr/bin/intel_residency
/usr/bin/intel_stepping
/usr/bin/intel_vbt_decode
/usr/bin/intel_watermark

%files data
%defattr(-,root,root,-)
/usr/share/igt-gpu-tools/1080p-left.png
/usr/share/igt-gpu-tools/1080p-right.png
/usr/share/igt-gpu-tools/README
/usr/share/igt-gpu-tools/fast-feedback.testlist
/usr/share/igt-gpu-tools/meta.testlist
/usr/share/igt-gpu-tools/pass.png
/usr/share/igt-gpu-tools/registers/audio_config_haswell_plus.txt
/usr/share/igt-gpu-tools/registers/audio_debug_haswell_plus.txt
/usr/share/igt-gpu-tools/registers/base_interrupt.txt
/usr/share/igt-gpu-tools/registers/base_other.txt
/usr/share/igt-gpu-tools/registers/base_power.txt
/usr/share/igt-gpu-tools/registers/base_rings.txt
/usr/share/igt-gpu-tools/registers/broadwell
/usr/share/igt-gpu-tools/registers/cherryview
/usr/share/igt-gpu-tools/registers/chv_display_base.txt
/usr/share/igt-gpu-tools/registers/chv_dpio_phy_x1.txt
/usr/share/igt-gpu-tools/registers/chv_dpio_phy_x2.txt
/usr/share/igt-gpu-tools/registers/chv_pipe_b_extra.txt
/usr/share/igt-gpu-tools/registers/chv_pipe_c.txt
/usr/share/igt-gpu-tools/registers/common_display.txt
/usr/share/igt-gpu-tools/registers/gen6_other.txt
/usr/share/igt-gpu-tools/registers/gen7_other.txt
/usr/share/igt-gpu-tools/registers/gen8_interrupt.txt
/usr/share/igt-gpu-tools/registers/gen8_other.txt
/usr/share/igt-gpu-tools/registers/haswell
/usr/share/igt-gpu-tools/registers/haswell_other.txt
/usr/share/igt-gpu-tools/registers/icelake
/usr/share/igt-gpu-tools/registers/icl_delta.txt
/usr/share/igt-gpu-tools/registers/ivybridge
/usr/share/igt-gpu-tools/registers/kabylake
/usr/share/igt-gpu-tools/registers/sandybridge
/usr/share/igt-gpu-tools/registers/skl_display.txt
/usr/share/igt-gpu-tools/registers/skl_powerwells.txt
/usr/share/igt-gpu-tools/registers/skylake
/usr/share/igt-gpu-tools/registers/valleyview
/usr/share/igt-gpu-tools/registers/vlv_cck.txt
/usr/share/igt-gpu-tools/registers/vlv_display_base.txt
/usr/share/igt-gpu-tools/registers/vlv_dpio_phy.txt
/usr/share/igt-gpu-tools/registers/vlv_dsi.txt
/usr/share/igt-gpu-tools/registers/vlv_flisdsi.txt
/usr/share/igt-gpu-tools/registers/vlv_pipe_a.txt
/usr/share/igt-gpu-tools/registers/vlv_pipe_b.txt
/usr/share/igt-gpu-tools/registers/vlv_power.txt

%files dev
%defattr(-,root,root,-)
/usr/lib64/intel_aubdump.so
/usr/lib64/libigt.so
/usr/lib64/pkgconfig/intel-gen4asm.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/igt-gpu-tools/annotation-glossary.html
/usr/share/gtk-doc/html/igt-gpu-tools/ch01.html
/usr/share/gtk-doc/html/igt-gpu-tools/ch02.html
/usr/share/gtk-doc/html/igt-gpu-tools/deprecated-api-index.html
/usr/share/gtk-doc/html/igt-gpu-tools/full-api-index.html
/usr/share/gtk-doc/html/igt-gpu-tools/home.png
/usr/share/gtk-doc/html/igt-gpu-tools/igt-amdgpu-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-chamelium-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-core-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-debugfs-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-drm-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gem-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gen3-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gen7-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-ALSA.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Audio.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Batch-Buffer.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Chamelium.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Chipset.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Core.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Draw.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Dummyload.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Frame.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Framebuffer.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-GEM-Context.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-GEM-Scheduler.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-GEM-Submission.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-GT.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-GVT.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-IO.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-KMS.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Power-Management.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Primes.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Random.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-SW-Sync.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-Stats.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-VC4.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-VGEM.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-aux.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-debugfs.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-drmtest.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-igt-device.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-ioctl-wrappers.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-kmod.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-syncobj.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-sysfs.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools-x86.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gpu-tools.devhelp2
/usr/share/gtk-doc/html/igt-gpu-tools/igt-gvt-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-i915-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-kms-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-meta-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-perf-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-pm-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-prime-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-sw-sync-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-test-programs-common-features.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-testdisplay-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-tools-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/igt-vgem-tests.html
/usr/share/gtk-doc/html/igt-gpu-tools/index.html
/usr/share/gtk-doc/html/igt-gpu-tools/left-insensitive.png
/usr/share/gtk-doc/html/igt-gpu-tools/left.png
/usr/share/gtk-doc/html/igt-gpu-tools/right-insensitive.png
/usr/share/gtk-doc/html/igt-gpu-tools/right.png
/usr/share/gtk-doc/html/igt-gpu-tools/style.css
/usr/share/gtk-doc/html/igt-gpu-tools/test-programs.html
/usr/share/gtk-doc/html/igt-gpu-tools/up-insensitive.png
/usr/share/gtk-doc/html/igt-gpu-tools/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/intel_aubdump.so.0
/usr/lib64/libigt.so.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/igt-gpu-tools/amdgpu/amd_abm
/usr/libexec/igt-gpu-tools/amdgpu/amd_basic
/usr/libexec/igt-gpu-tools/amdgpu/amd_color
/usr/libexec/igt-gpu-tools/amdgpu/amd_cs_nop
/usr/libexec/igt-gpu-tools/amdgpu/amd_prime
/usr/libexec/igt-gpu-tools/benchmarks/gem_blt
/usr/libexec/igt-gpu-tools/benchmarks/gem_busy
/usr/libexec/igt-gpu-tools/benchmarks/gem_create
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_ctx
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_fault
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_nop
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_reloc
/usr/libexec/igt-gpu-tools/benchmarks/gem_exec_trace
/usr/libexec/igt-gpu-tools/benchmarks/gem_latency
/usr/libexec/igt-gpu-tools/benchmarks/gem_mmap
/usr/libexec/igt-gpu-tools/benchmarks/gem_prw
/usr/libexec/igt-gpu-tools/benchmarks/gem_set_domain
/usr/libexec/igt-gpu-tools/benchmarks/gem_syslatency
/usr/libexec/igt-gpu-tools/benchmarks/gem_userptr_benchmark
/usr/libexec/igt-gpu-tools/benchmarks/gem_wsim
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large_gtt
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_large_map
/usr/libexec/igt-gpu-tools/benchmarks/intel_upload_blit_small
/usr/libexec/igt-gpu-tools/benchmarks/kms_vblank
/usr/libexec/igt-gpu-tools/benchmarks/prime_lookup
/usr/libexec/igt-gpu-tools/benchmarks/vgem_mmap
/usr/libexec/igt-gpu-tools/core_auth
/usr/libexec/igt-gpu-tools/core_getclient
/usr/libexec/igt-gpu-tools/core_getstats
/usr/libexec/igt-gpu-tools/core_getversion
/usr/libexec/igt-gpu-tools/core_setmaster_vs_auth
/usr/libexec/igt-gpu-tools/debugfs_test
/usr/libexec/igt-gpu-tools/drm_import_export
/usr/libexec/igt-gpu-tools/drm_mm
/usr/libexec/igt-gpu-tools/drm_read
/usr/libexec/igt-gpu-tools/gem_bad_reloc
/usr/libexec/igt-gpu-tools/gem_basic
/usr/libexec/igt-gpu-tools/gem_busy
/usr/libexec/igt-gpu-tools/gem_caching
/usr/libexec/igt-gpu-tools/gem_close
/usr/libexec/igt-gpu-tools/gem_close_race
/usr/libexec/igt-gpu-tools/gem_concurrent_blit
/usr/libexec/igt-gpu-tools/gem_cpu_reloc
/usr/libexec/igt-gpu-tools/gem_create
/usr/libexec/igt-gpu-tools/gem_cs_prefetch
/usr/libexec/igt-gpu-tools/gem_cs_tlb
/usr/libexec/igt-gpu-tools/gem_ctx_bad_destroy
/usr/libexec/igt-gpu-tools/gem_ctx_clone
/usr/libexec/igt-gpu-tools/gem_ctx_create
/usr/libexec/igt-gpu-tools/gem_ctx_engines
/usr/libexec/igt-gpu-tools/gem_ctx_exec
/usr/libexec/igt-gpu-tools/gem_ctx_isolation
/usr/libexec/igt-gpu-tools/gem_ctx_param
/usr/libexec/igt-gpu-tools/gem_ctx_shared
/usr/libexec/igt-gpu-tools/gem_ctx_sseu
/usr/libexec/igt-gpu-tools/gem_ctx_switch
/usr/libexec/igt-gpu-tools/gem_ctx_thrash
/usr/libexec/igt-gpu-tools/gem_double_irq_loop
/usr/libexec/igt-gpu-tools/gem_eio
/usr/libexec/igt-gpu-tools/gem_evict_alignment
/usr/libexec/igt-gpu-tools/gem_evict_everything
/usr/libexec/igt-gpu-tools/gem_exec_alignment
/usr/libexec/igt-gpu-tools/gem_exec_async
/usr/libexec/igt-gpu-tools/gem_exec_await
/usr/libexec/igt-gpu-tools/gem_exec_bad_domains
/usr/libexec/igt-gpu-tools/gem_exec_balancer
/usr/libexec/igt-gpu-tools/gem_exec_basic
/usr/libexec/igt-gpu-tools/gem_exec_big
/usr/libexec/igt-gpu-tools/gem_exec_blt
/usr/libexec/igt-gpu-tools/gem_exec_capture
/usr/libexec/igt-gpu-tools/gem_exec_create
/usr/libexec/igt-gpu-tools/gem_exec_faulting_reloc
/usr/libexec/igt-gpu-tools/gem_exec_fence
/usr/libexec/igt-gpu-tools/gem_exec_flush
/usr/libexec/igt-gpu-tools/gem_exec_gttfill
/usr/libexec/igt-gpu-tools/gem_exec_latency
/usr/libexec/igt-gpu-tools/gem_exec_lut_handle
/usr/libexec/igt-gpu-tools/gem_exec_nop
/usr/libexec/igt-gpu-tools/gem_exec_parallel
/usr/libexec/igt-gpu-tools/gem_exec_params
/usr/libexec/igt-gpu-tools/gem_exec_parse
/usr/libexec/igt-gpu-tools/gem_exec_reloc
/usr/libexec/igt-gpu-tools/gem_exec_reuse
/usr/libexec/igt-gpu-tools/gem_exec_schedule
/usr/libexec/igt-gpu-tools/gem_exec_store
/usr/libexec/igt-gpu-tools/gem_exec_suspend
/usr/libexec/igt-gpu-tools/gem_exec_whisper
/usr/libexec/igt-gpu-tools/gem_fd_exhaustion
/usr/libexec/igt-gpu-tools/gem_fence_thrash
/usr/libexec/igt-gpu-tools/gem_fence_upload
/usr/libexec/igt-gpu-tools/gem_fenced_exec_thrash
/usr/libexec/igt-gpu-tools/gem_flink_basic
/usr/libexec/igt-gpu-tools/gem_flink_race
/usr/libexec/igt-gpu-tools/gem_gpgpu_fill
/usr/libexec/igt-gpu-tools/gem_gtt_cpu_tlb
/usr/libexec/igt-gpu-tools/gem_gtt_hog
/usr/libexec/igt-gpu-tools/gem_gtt_speed
/usr/libexec/igt-gpu-tools/gem_largeobject
/usr/libexec/igt-gpu-tools/gem_linear_blits
/usr/libexec/igt-gpu-tools/gem_lut_handle
/usr/libexec/igt-gpu-tools/gem_madvise
/usr/libexec/igt-gpu-tools/gem_media_fill
/usr/libexec/igt-gpu-tools/gem_media_vme
/usr/libexec/igt-gpu-tools/gem_mmap
/usr/libexec/igt-gpu-tools/gem_mmap_gtt
/usr/libexec/igt-gpu-tools/gem_mmap_offset_exhaustion
/usr/libexec/igt-gpu-tools/gem_mmap_wc
/usr/libexec/igt-gpu-tools/gem_mocs_settings
/usr/libexec/igt-gpu-tools/gem_partial_pwrite_pread
/usr/libexec/igt-gpu-tools/gem_persistent_relocs
/usr/libexec/igt-gpu-tools/gem_pipe_control_store_loop
/usr/libexec/igt-gpu-tools/gem_ppgtt
/usr/libexec/igt-gpu-tools/gem_pread
/usr/libexec/igt-gpu-tools/gem_pread_after_blit
/usr/libexec/igt-gpu-tools/gem_pwrite
/usr/libexec/igt-gpu-tools/gem_pwrite_pread
/usr/libexec/igt-gpu-tools/gem_pwrite_snooped
/usr/libexec/igt-gpu-tools/gem_read_read_speed
/usr/libexec/igt-gpu-tools/gem_readwrite
/usr/libexec/igt-gpu-tools/gem_reg_read
/usr/libexec/igt-gpu-tools/gem_reloc_overflow
/usr/libexec/igt-gpu-tools/gem_reloc_vs_gpu
/usr/libexec/igt-gpu-tools/gem_render_copy
/usr/libexec/igt-gpu-tools/gem_render_copy_redux
/usr/libexec/igt-gpu-tools/gem_render_linear_blits
/usr/libexec/igt-gpu-tools/gem_render_tiled_blits
/usr/libexec/igt-gpu-tools/gem_request_retire
/usr/libexec/igt-gpu-tools/gem_reset_stats
/usr/libexec/igt-gpu-tools/gem_ring_sync_copy
/usr/libexec/igt-gpu-tools/gem_ring_sync_loop
/usr/libexec/igt-gpu-tools/gem_ringfill
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_blt
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_gtt
/usr/libexec/igt-gpu-tools/gem_set_tiling_vs_pwrite
/usr/libexec/igt-gpu-tools/gem_shrink
/usr/libexec/igt-gpu-tools/gem_softpin
/usr/libexec/igt-gpu-tools/gem_spin_batch
/usr/libexec/igt-gpu-tools/gem_stolen
/usr/libexec/igt-gpu-tools/gem_storedw_batches_loop
/usr/libexec/igt-gpu-tools/gem_storedw_loop
/usr/libexec/igt-gpu-tools/gem_streaming_writes
/usr/libexec/igt-gpu-tools/gem_stress
/usr/libexec/igt-gpu-tools/gem_sync
/usr/libexec/igt-gpu-tools/gem_threaded_access_tiled
/usr/libexec/igt-gpu-tools/gem_tiled_blits
/usr/libexec/igt-gpu-tools/gem_tiled_fence_blits
/usr/libexec/igt-gpu-tools/gem_tiled_partial_pwrite_pread
/usr/libexec/igt-gpu-tools/gem_tiled_pread_basic
/usr/libexec/igt-gpu-tools/gem_tiled_pread_pwrite
/usr/libexec/igt-gpu-tools/gem_tiled_swapping
/usr/libexec/igt-gpu-tools/gem_tiled_wb
/usr/libexec/igt-gpu-tools/gem_tiled_wc
/usr/libexec/igt-gpu-tools/gem_tiling_max_stride
/usr/libexec/igt-gpu-tools/gem_unfence_active_buffers
/usr/libexec/igt-gpu-tools/gem_unref_active_buffers
/usr/libexec/igt-gpu-tools/gem_userptr_blits
/usr/libexec/igt-gpu-tools/gem_vm_create
/usr/libexec/igt-gpu-tools/gem_wait
/usr/libexec/igt-gpu-tools/gem_workarounds
/usr/libexec/igt-gpu-tools/gem_write_read_ring_switch
/usr/libexec/igt-gpu-tools/gen3_mixed_blits
/usr/libexec/igt-gpu-tools/gen3_render_linear_blits
/usr/libexec/igt-gpu-tools/gen3_render_mixed_blits
/usr/libexec/igt-gpu-tools/gen3_render_tiledx_blits
/usr/libexec/igt-gpu-tools/gen3_render_tiledy_blits
/usr/libexec/igt-gpu-tools/i915_fb_tiling
/usr/libexec/igt-gpu-tools/i915_getparams_basic
/usr/libexec/igt-gpu-tools/i915_hangman
/usr/libexec/igt-gpu-tools/i915_module_load
/usr/libexec/igt-gpu-tools/i915_pm_backlight
/usr/libexec/igt-gpu-tools/i915_pm_lpsp
/usr/libexec/igt-gpu-tools/i915_pm_rc6_residency
/usr/libexec/igt-gpu-tools/i915_pm_rpm
/usr/libexec/igt-gpu-tools/i915_pm_rps
/usr/libexec/igt-gpu-tools/i915_pm_sseu
/usr/libexec/igt-gpu-tools/i915_query
/usr/libexec/igt-gpu-tools/i915_selftest
/usr/libexec/igt-gpu-tools/i915_suspend
/usr/libexec/igt-gpu-tools/kms_3d
/usr/libexec/igt-gpu-tools/kms_addfb_basic
/usr/libexec/igt-gpu-tools/kms_atomic
/usr/libexec/igt-gpu-tools/kms_atomic_interruptible
/usr/libexec/igt-gpu-tools/kms_atomic_transition
/usr/libexec/igt-gpu-tools/kms_available_modes_crc
/usr/libexec/igt-gpu-tools/kms_big_fb
/usr/libexec/igt-gpu-tools/kms_busy
/usr/libexec/igt-gpu-tools/kms_ccs
/usr/libexec/igt-gpu-tools/kms_color
/usr/libexec/igt-gpu-tools/kms_concurrent
/usr/libexec/igt-gpu-tools/kms_content_protection
/usr/libexec/igt-gpu-tools/kms_crtc_background_color
/usr/libexec/igt-gpu-tools/kms_cursor_crc
/usr/libexec/igt-gpu-tools/kms_cursor_edge_walk
/usr/libexec/igt-gpu-tools/kms_cursor_legacy
/usr/libexec/igt-gpu-tools/kms_dp_dsc
/usr/libexec/igt-gpu-tools/kms_draw_crc
/usr/libexec/igt-gpu-tools/kms_fbcon_fbt
/usr/libexec/igt-gpu-tools/kms_fence_pin_leak
/usr/libexec/igt-gpu-tools/kms_flip
/usr/libexec/igt-gpu-tools/kms_flip_event_leak
/usr/libexec/igt-gpu-tools/kms_flip_tiling
/usr/libexec/igt-gpu-tools/kms_force_connector_basic
/usr/libexec/igt-gpu-tools/kms_frontbuffer_tracking
/usr/libexec/igt-gpu-tools/kms_getfb
/usr/libexec/igt-gpu-tools/kms_hdmi_inject
/usr/libexec/igt-gpu-tools/kms_invalid_dotclock
/usr/libexec/igt-gpu-tools/kms_lease
/usr/libexec/igt-gpu-tools/kms_legacy_colorkey
/usr/libexec/igt-gpu-tools/kms_mmap_write_crc
/usr/libexec/igt-gpu-tools/kms_panel_fitting
/usr/libexec/igt-gpu-tools/kms_pipe_b_c_ivb
/usr/libexec/igt-gpu-tools/kms_pipe_crc_basic
/usr/libexec/igt-gpu-tools/kms_plane
/usr/libexec/igt-gpu-tools/kms_plane_alpha_blend
/usr/libexec/igt-gpu-tools/kms_plane_cursor
/usr/libexec/igt-gpu-tools/kms_plane_lowres
/usr/libexec/igt-gpu-tools/kms_plane_multiple
/usr/libexec/igt-gpu-tools/kms_plane_scaling
/usr/libexec/igt-gpu-tools/kms_prop_blob
/usr/libexec/igt-gpu-tools/kms_properties
/usr/libexec/igt-gpu-tools/kms_psr
/usr/libexec/igt-gpu-tools/kms_psr2_su
/usr/libexec/igt-gpu-tools/kms_pwrite_crc
/usr/libexec/igt-gpu-tools/kms_rmfb
/usr/libexec/igt-gpu-tools/kms_rotation_crc
/usr/libexec/igt-gpu-tools/kms_selftest
/usr/libexec/igt-gpu-tools/kms_sequence
/usr/libexec/igt-gpu-tools/kms_setmode
/usr/libexec/igt-gpu-tools/kms_sysfs_edid_timing
/usr/libexec/igt-gpu-tools/kms_tv_load_detect
/usr/libexec/igt-gpu-tools/kms_universal_plane
/usr/libexec/igt-gpu-tools/kms_vblank
/usr/libexec/igt-gpu-tools/kms_vrr
/usr/libexec/igt-gpu-tools/meta_test
/usr/libexec/igt-gpu-tools/panfrost_gem_new
/usr/libexec/igt-gpu-tools/panfrost_get_param
/usr/libexec/igt-gpu-tools/panfrost_prime
/usr/libexec/igt-gpu-tools/panfrost_submit
/usr/libexec/igt-gpu-tools/perf
/usr/libexec/igt-gpu-tools/perf_pmu
/usr/libexec/igt-gpu-tools/prime_busy
/usr/libexec/igt-gpu-tools/prime_mmap
/usr/libexec/igt-gpu-tools/prime_mmap_coherency
/usr/libexec/igt-gpu-tools/prime_mmap_kms
/usr/libexec/igt-gpu-tools/prime_nv_api
/usr/libexec/igt-gpu-tools/prime_nv_pcopy
/usr/libexec/igt-gpu-tools/prime_nv_test
/usr/libexec/igt-gpu-tools/prime_self_import
/usr/libexec/igt-gpu-tools/prime_udl
/usr/libexec/igt-gpu-tools/prime_vgem
/usr/libexec/igt-gpu-tools/sw_sync
/usr/libexec/igt-gpu-tools/syncobj_basic
/usr/libexec/igt-gpu-tools/syncobj_wait
/usr/libexec/igt-gpu-tools/template
/usr/libexec/igt-gpu-tools/test-list.txt
/usr/libexec/igt-gpu-tools/testdisplay
/usr/libexec/igt-gpu-tools/tools_test
/usr/libexec/igt-gpu-tools/v3d_get_bo_offset
/usr/libexec/igt-gpu-tools/v3d_get_param
/usr/libexec/igt-gpu-tools/v3d_mmap
/usr/libexec/igt-gpu-tools/vc4_create_bo
/usr/libexec/igt-gpu-tools/vc4_dmabuf_poll
/usr/libexec/igt-gpu-tools/vc4_label_bo
/usr/libexec/igt-gpu-tools/vc4_lookup_fail
/usr/libexec/igt-gpu-tools/vc4_purgeable_bo
/usr/libexec/igt-gpu-tools/vc4_tiling
/usr/libexec/igt-gpu-tools/vc4_wait_bo
/usr/libexec/igt-gpu-tools/vc4_wait_seqno
/usr/libexec/igt-gpu-tools/vgem_basic
/usr/libexec/igt-gpu-tools/vgem_slow

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/igt-gpu-tools/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/intel_aubdump.1.gz
/usr/share/man/man1/intel_audio_dump.1.gz
/usr/share/man/man1/intel_bios_dumper.1.gz
/usr/share/man/man1/intel_error_decode.1.gz
/usr/share/man/man1/intel_gpu_frequency.1.gz
/usr/share/man/man1/intel_gpu_top.1.gz
/usr/share/man/man1/intel_gtt.1.gz
/usr/share/man/man1/intel_infoframes.1.gz
/usr/share/man/man1/intel_lid.1.gz
/usr/share/man/man1/intel_panel_fitter.1.gz
/usr/share/man/man1/intel_reg.1.gz
/usr/share/man/man1/intel_stepping.1.gz
/usr/share/man/man1/intel_upload_blit_large.1.gz
/usr/share/man/man1/intel_upload_blit_large_gtt.1.gz
/usr/share/man/man1/intel_upload_blit_large_map.1.gz
/usr/share/man/man1/intel_upload_blit_small.1.gz
/usr/share/man/man1/intel_vbt_decode.1.gz
