#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7370055DB74C2475 (petri.latvala@intel.com)
#
Name     : intel-gpu-tools
Version  : 1.22
Release  : 3
URL      : https://xorg.freedesktop.org/releases/individual/app/intel-gpu-tools-1.22.tar.xz
Source0  : https://xorg.freedesktop.org/releases/individual/app/intel-gpu-tools-1.22.tar.xz
Source99 : https://xorg.freedesktop.org/releases/individual/app/intel-gpu-tools-1.22.tar.xz.sig
Summary  : An assembler compiler for the Intel 965+ Chipset
Group    : Development/Tools
License  : MIT
Requires: intel-gpu-tools-bin
Requires: intel-gpu-tools-data
BuildRequires : bison
BuildRequires : docbook-xml
BuildRequires : flex
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_amdgpu)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libdrm_nouveau)
BuildRequires : pkgconfig(libkmod)
BuildRequires : pkgconfig(libprocps)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xv)
BuildRequires : python3
Patch1: build.patch

%description
Intel GPU Tools
===============
Description
-----------
Intel GPU Tools is a collection of tools for development and testing of the
Intel DRM driver. There are many macro-level test suites that get used against
the driver, including xtest, rendercheck, piglit, and oglconform, but failures
from those can be difficult to track down to kernel changes, and many require
complicated build procedures or specific testing environments to get useful
results. Therefore, Intel GPU Tools includes low-level tools and tests
specifically for development and testing of the Intel DRM Driver.

%package bin
Summary: bin components for the intel-gpu-tools package.
Group: Binaries
Requires: intel-gpu-tools-data

%description bin
bin components for the intel-gpu-tools package.


%package data
Summary: data components for the intel-gpu-tools package.
Group: Data

%description data
data components for the intel-gpu-tools package.


%package dev
Summary: dev components for the intel-gpu-tools package.
Group: Development
Requires: intel-gpu-tools-bin
Requires: intel-gpu-tools-data
Provides: intel-gpu-tools-devel

%description dev
dev components for the intel-gpu-tools package.


%prep
%setup -q -n intel-gpu-tools-1.22
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525479165
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/intel-gen4asm
/usr/bin/intel-gen4disasm
/usr/bin/intel_aubdump
/usr/bin/intel_audio_dump
/usr/bin/intel_backlight
/usr/bin/intel_bios_dumper
/usr/bin/intel_display_crc
/usr/bin/intel_display_poller
/usr/bin/intel_dp_compliance
/usr/bin/intel_dump_decode
/usr/bin/intel_error_decode
/usr/bin/intel_firmware_decode
/usr/bin/intel_forcewaked
/usr/bin/intel_framebuffer_dump
/usr/bin/intel_gem_info
/usr/bin/intel_gpu_abrt
/usr/bin/intel_gpu_frequency
/usr/bin/intel_gpu_time
/usr/bin/intel_gpu_top
/usr/bin/intel_gtt
/usr/bin/intel_guc_logger
/usr/bin/intel_gvtg_test
/usr/bin/intel_infoframes
/usr/bin/intel_l3_parity
/usr/bin/intel_lid
/usr/bin/intel_opregion_decode
/usr/bin/intel_panel_fitter
/usr/bin/intel_perf_counters
/usr/bin/intel_reg
/usr/bin/intel_reg_checker
/usr/bin/intel_residency
/usr/bin/intel_stepping
/usr/bin/intel_vbt_decode
/usr/bin/intel_watermark
/usr/libexec/intel-gpu-tools/amd_basic
/usr/libexec/intel-gpu-tools/amd_cs_nop
/usr/libexec/intel-gpu-tools/amd_prime
/usr/libexec/intel-gpu-tools/audio
/usr/libexec/intel-gpu-tools/benchmarks/gem_blt_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_busy_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_create_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_exec_ctx_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_exec_fault_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_exec_nop_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_exec_reloc_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_exec_trace_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_latency_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_mmap_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_prw_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_set_domain_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_syslatency_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_userptr_benchmark_bench
/usr/libexec/intel-gpu-tools/benchmarks/gem_wsim_bench
/usr/libexec/intel-gpu-tools/benchmarks/intel_upload_blit_large_bench
/usr/libexec/intel-gpu-tools/benchmarks/intel_upload_blit_large_gtt_bench
/usr/libexec/intel-gpu-tools/benchmarks/intel_upload_blit_large_map_bench
/usr/libexec/intel-gpu-tools/benchmarks/intel_upload_blit_small_bench
/usr/libexec/intel-gpu-tools/benchmarks/kms_vblank_bench
/usr/libexec/intel-gpu-tools/benchmarks/prime_lookup_bench
/usr/libexec/intel-gpu-tools/benchmarks/vgem_mmap_bench
/usr/libexec/intel-gpu-tools/core_auth
/usr/libexec/intel-gpu-tools/core_get_client_auth
/usr/libexec/intel-gpu-tools/core_getclient
/usr/libexec/intel-gpu-tools/core_getstats
/usr/libexec/intel-gpu-tools/core_getversion
/usr/libexec/intel-gpu-tools/core_prop_blob
/usr/libexec/intel-gpu-tools/core_setmaster_vs_auth
/usr/libexec/intel-gpu-tools/debugfs_test
/usr/libexec/intel-gpu-tools/drm_import_export
/usr/libexec/intel-gpu-tools/drm_mm
/usr/libexec/intel-gpu-tools/drm_read
/usr/libexec/intel-gpu-tools/drm_vma_limiter
/usr/libexec/intel-gpu-tools/drm_vma_limiter_cached
/usr/libexec/intel-gpu-tools/drm_vma_limiter_cpu
/usr/libexec/intel-gpu-tools/drm_vma_limiter_gtt
/usr/libexec/intel-gpu-tools/drv_getparams_basic
/usr/libexec/intel-gpu-tools/drv_hangman
/usr/libexec/intel-gpu-tools/drv_missed_irq
/usr/libexec/intel-gpu-tools/drv_module_reload
/usr/libexec/intel-gpu-tools/drv_selftest
/usr/libexec/intel-gpu-tools/drv_suspend
/usr/libexec/intel-gpu-tools/gem_bad_reloc
/usr/libexec/intel-gpu-tools/gem_basic
/usr/libexec/intel-gpu-tools/gem_busy
/usr/libexec/intel-gpu-tools/gem_caching
/usr/libexec/intel-gpu-tools/gem_close
/usr/libexec/intel-gpu-tools/gem_close_race
/usr/libexec/intel-gpu-tools/gem_concurrent_blit
/usr/libexec/intel-gpu-tools/gem_cpu_reloc
/usr/libexec/intel-gpu-tools/gem_create
/usr/libexec/intel-gpu-tools/gem_cs_prefetch
/usr/libexec/intel-gpu-tools/gem_cs_tlb
/usr/libexec/intel-gpu-tools/gem_ctx_bad_destroy
/usr/libexec/intel-gpu-tools/gem_ctx_bad_exec
/usr/libexec/intel-gpu-tools/gem_ctx_create
/usr/libexec/intel-gpu-tools/gem_ctx_exec
/usr/libexec/intel-gpu-tools/gem_ctx_isolation
/usr/libexec/intel-gpu-tools/gem_ctx_param
/usr/libexec/intel-gpu-tools/gem_ctx_switch
/usr/libexec/intel-gpu-tools/gem_ctx_thrash
/usr/libexec/intel-gpu-tools/gem_double_irq_loop
/usr/libexec/intel-gpu-tools/gem_eio
/usr/libexec/intel-gpu-tools/gem_evict_alignment
/usr/libexec/intel-gpu-tools/gem_evict_everything
/usr/libexec/intel-gpu-tools/gem_exec_alignment
/usr/libexec/intel-gpu-tools/gem_exec_async
/usr/libexec/intel-gpu-tools/gem_exec_await
/usr/libexec/intel-gpu-tools/gem_exec_bad_domains
/usr/libexec/intel-gpu-tools/gem_exec_basic
/usr/libexec/intel-gpu-tools/gem_exec_big
/usr/libexec/intel-gpu-tools/gem_exec_blt
/usr/libexec/intel-gpu-tools/gem_exec_capture
/usr/libexec/intel-gpu-tools/gem_exec_create
/usr/libexec/intel-gpu-tools/gem_exec_faulting_reloc
/usr/libexec/intel-gpu-tools/gem_exec_fence
/usr/libexec/intel-gpu-tools/gem_exec_flush
/usr/libexec/intel-gpu-tools/gem_exec_gttfill
/usr/libexec/intel-gpu-tools/gem_exec_latency
/usr/libexec/intel-gpu-tools/gem_exec_lut_handle
/usr/libexec/intel-gpu-tools/gem_exec_nop
/usr/libexec/intel-gpu-tools/gem_exec_parallel
/usr/libexec/intel-gpu-tools/gem_exec_params
/usr/libexec/intel-gpu-tools/gem_exec_parse
/usr/libexec/intel-gpu-tools/gem_exec_reloc
/usr/libexec/intel-gpu-tools/gem_exec_reuse
/usr/libexec/intel-gpu-tools/gem_exec_schedule
/usr/libexec/intel-gpu-tools/gem_exec_store
/usr/libexec/intel-gpu-tools/gem_exec_suspend
/usr/libexec/intel-gpu-tools/gem_exec_whisper
/usr/libexec/intel-gpu-tools/gem_fd_exhaustion
/usr/libexec/intel-gpu-tools/gem_fence_thrash
/usr/libexec/intel-gpu-tools/gem_fence_upload
/usr/libexec/intel-gpu-tools/gem_fenced_exec_thrash
/usr/libexec/intel-gpu-tools/gem_flink_basic
/usr/libexec/intel-gpu-tools/gem_flink_race
/usr/libexec/intel-gpu-tools/gem_gpgpu_fill
/usr/libexec/intel-gpu-tools/gem_gtt_cpu_tlb
/usr/libexec/intel-gpu-tools/gem_gtt_hog
/usr/libexec/intel-gpu-tools/gem_gtt_speed
/usr/libexec/intel-gpu-tools/gem_largeobject
/usr/libexec/intel-gpu-tools/gem_linear_blits
/usr/libexec/intel-gpu-tools/gem_lut_handle
/usr/libexec/intel-gpu-tools/gem_madvise
/usr/libexec/intel-gpu-tools/gem_media_fill
/usr/libexec/intel-gpu-tools/gem_mmap
/usr/libexec/intel-gpu-tools/gem_mmap_gtt
/usr/libexec/intel-gpu-tools/gem_mmap_offset_exhaustion
/usr/libexec/intel-gpu-tools/gem_mmap_wc
/usr/libexec/intel-gpu-tools/gem_mocs_settings
/usr/libexec/intel-gpu-tools/gem_partial_pwrite_pread
/usr/libexec/intel-gpu-tools/gem_persistent_relocs
/usr/libexec/intel-gpu-tools/gem_pipe_control_store_loop
/usr/libexec/intel-gpu-tools/gem_ppgtt
/usr/libexec/intel-gpu-tools/gem_pread
/usr/libexec/intel-gpu-tools/gem_pread_after_blit
/usr/libexec/intel-gpu-tools/gem_pwrite
/usr/libexec/intel-gpu-tools/gem_pwrite_pread
/usr/libexec/intel-gpu-tools/gem_pwrite_snooped
/usr/libexec/intel-gpu-tools/gem_read_read_speed
/usr/libexec/intel-gpu-tools/gem_readwrite
/usr/libexec/intel-gpu-tools/gem_reg_read
/usr/libexec/intel-gpu-tools/gem_reloc_overflow
/usr/libexec/intel-gpu-tools/gem_reloc_vs_gpu
/usr/libexec/intel-gpu-tools/gem_render_copy
/usr/libexec/intel-gpu-tools/gem_render_copy_redux
/usr/libexec/intel-gpu-tools/gem_render_linear_blits
/usr/libexec/intel-gpu-tools/gem_render_tiled_blits
/usr/libexec/intel-gpu-tools/gem_request_retire
/usr/libexec/intel-gpu-tools/gem_reset_stats
/usr/libexec/intel-gpu-tools/gem_ring_sync_copy
/usr/libexec/intel-gpu-tools/gem_ring_sync_loop
/usr/libexec/intel-gpu-tools/gem_ringfill
/usr/libexec/intel-gpu-tools/gem_set_tiling_vs_blt
/usr/libexec/intel-gpu-tools/gem_set_tiling_vs_gtt
/usr/libexec/intel-gpu-tools/gem_set_tiling_vs_pwrite
/usr/libexec/intel-gpu-tools/gem_shrink
/usr/libexec/intel-gpu-tools/gem_softpin
/usr/libexec/intel-gpu-tools/gem_spin_batch
/usr/libexec/intel-gpu-tools/gem_stolen
/usr/libexec/intel-gpu-tools/gem_storedw_batches_loop
/usr/libexec/intel-gpu-tools/gem_storedw_loop
/usr/libexec/intel-gpu-tools/gem_streaming_writes
/usr/libexec/intel-gpu-tools/gem_stress
/usr/libexec/intel-gpu-tools/gem_sync
/usr/libexec/intel-gpu-tools/gem_threaded_access_tiled
/usr/libexec/intel-gpu-tools/gem_tiled_blits
/usr/libexec/intel-gpu-tools/gem_tiled_fence_blits
/usr/libexec/intel-gpu-tools/gem_tiled_partial_pwrite_pread
/usr/libexec/intel-gpu-tools/gem_tiled_pread_basic
/usr/libexec/intel-gpu-tools/gem_tiled_pread_pwrite
/usr/libexec/intel-gpu-tools/gem_tiled_swapping
/usr/libexec/intel-gpu-tools/gem_tiled_wb
/usr/libexec/intel-gpu-tools/gem_tiled_wc
/usr/libexec/intel-gpu-tools/gem_tiling_max_stride
/usr/libexec/intel-gpu-tools/gem_unfence_active_buffers
/usr/libexec/intel-gpu-tools/gem_unref_active_buffers
/usr/libexec/intel-gpu-tools/gem_userptr_blits
/usr/libexec/intel-gpu-tools/gem_wait
/usr/libexec/intel-gpu-tools/gem_workarounds
/usr/libexec/intel-gpu-tools/gem_write_read_ring_switch
/usr/libexec/intel-gpu-tools/gen3_mixed_blits
/usr/libexec/intel-gpu-tools/gen3_render_linear_blits
/usr/libexec/intel-gpu-tools/gen3_render_mixed_blits
/usr/libexec/intel-gpu-tools/gen3_render_tiledx_blits
/usr/libexec/intel-gpu-tools/gen3_render_tiledy_blits
/usr/libexec/intel-gpu-tools/gvt_basic
/usr/libexec/intel-gpu-tools/kms_3d
/usr/libexec/intel-gpu-tools/kms_addfb_basic
/usr/libexec/intel-gpu-tools/kms_atomic
/usr/libexec/intel-gpu-tools/kms_atomic_interruptible
/usr/libexec/intel-gpu-tools/kms_atomic_transition
/usr/libexec/intel-gpu-tools/kms_busy
/usr/libexec/intel-gpu-tools/kms_ccs
/usr/libexec/intel-gpu-tools/kms_chv_cursor_fail
/usr/libexec/intel-gpu-tools/kms_color
/usr/libexec/intel-gpu-tools/kms_concurrent
/usr/libexec/intel-gpu-tools/kms_crtc_background_color
/usr/libexec/intel-gpu-tools/kms_cursor_crc
/usr/libexec/intel-gpu-tools/kms_cursor_legacy
/usr/libexec/intel-gpu-tools/kms_draw_crc
/usr/libexec/intel-gpu-tools/kms_fbcon_fbt
/usr/libexec/intel-gpu-tools/kms_fence_pin_leak
/usr/libexec/intel-gpu-tools/kms_flip
/usr/libexec/intel-gpu-tools/kms_flip_event_leak
/usr/libexec/intel-gpu-tools/kms_flip_tiling
/usr/libexec/intel-gpu-tools/kms_force_connector_basic
/usr/libexec/intel-gpu-tools/kms_frontbuffer_tracking
/usr/libexec/intel-gpu-tools/kms_hdmi_inject
/usr/libexec/intel-gpu-tools/kms_invalid_dotclock
/usr/libexec/intel-gpu-tools/kms_legacy_colorkey
/usr/libexec/intel-gpu-tools/kms_mmap_write_crc
/usr/libexec/intel-gpu-tools/kms_mmio_vs_cs_flip
/usr/libexec/intel-gpu-tools/kms_panel_fitting
/usr/libexec/intel-gpu-tools/kms_pipe_b_c_ivb
/usr/libexec/intel-gpu-tools/kms_pipe_crc_basic
/usr/libexec/intel-gpu-tools/kms_plane
/usr/libexec/intel-gpu-tools/kms_plane_lowres
/usr/libexec/intel-gpu-tools/kms_plane_multiple
/usr/libexec/intel-gpu-tools/kms_plane_scaling
/usr/libexec/intel-gpu-tools/kms_properties
/usr/libexec/intel-gpu-tools/kms_psr_sink_crc
/usr/libexec/intel-gpu-tools/kms_pwrite_crc
/usr/libexec/intel-gpu-tools/kms_rmfb
/usr/libexec/intel-gpu-tools/kms_rotation_crc
/usr/libexec/intel-gpu-tools/kms_setmode
/usr/libexec/intel-gpu-tools/kms_sink_crc_basic
/usr/libexec/intel-gpu-tools/kms_sysfs_edid_timing
/usr/libexec/intel-gpu-tools/kms_tv_load_detect
/usr/libexec/intel-gpu-tools/kms_universal_plane
/usr/libexec/intel-gpu-tools/kms_vblank
/usr/libexec/intel-gpu-tools/meta_test
/usr/libexec/intel-gpu-tools/perf
/usr/libexec/intel-gpu-tools/perf_pmu
/usr/libexec/intel-gpu-tools/pm_backlight
/usr/libexec/intel-gpu-tools/pm_lpsp
/usr/libexec/intel-gpu-tools/pm_rc6_residency
/usr/libexec/intel-gpu-tools/pm_rpm
/usr/libexec/intel-gpu-tools/pm_rps
/usr/libexec/intel-gpu-tools/pm_sseu
/usr/libexec/intel-gpu-tools/prime_busy
/usr/libexec/intel-gpu-tools/prime_mmap
/usr/libexec/intel-gpu-tools/prime_mmap_coherency
/usr/libexec/intel-gpu-tools/prime_mmap_kms
/usr/libexec/intel-gpu-tools/prime_nv_api
/usr/libexec/intel-gpu-tools/prime_nv_pcopy
/usr/libexec/intel-gpu-tools/prime_nv_test
/usr/libexec/intel-gpu-tools/prime_self_import
/usr/libexec/intel-gpu-tools/prime_udl
/usr/libexec/intel-gpu-tools/prime_vgem
/usr/libexec/intel-gpu-tools/sw_sync
/usr/libexec/intel-gpu-tools/syncobj_basic
/usr/libexec/intel-gpu-tools/syncobj_wait
/usr/libexec/intel-gpu-tools/template
/usr/libexec/intel-gpu-tools/test-list.txt
/usr/libexec/intel-gpu-tools/testdisplay
/usr/libexec/intel-gpu-tools/tools_test
/usr/libexec/intel-gpu-tools/vc4_create_bo
/usr/libexec/intel-gpu-tools/vc4_dmabuf_poll
/usr/libexec/intel-gpu-tools/vc4_label_bo
/usr/libexec/intel-gpu-tools/vc4_lookup_fail
/usr/libexec/intel-gpu-tools/vc4_purgeable_bo
/usr/libexec/intel-gpu-tools/vc4_tiling
/usr/libexec/intel-gpu-tools/vc4_wait_bo
/usr/libexec/intel-gpu-tools/vc4_wait_seqno
/usr/libexec/intel-gpu-tools/vgem_basic
/usr/libexec/intel-gpu-tools/vgem_slow

%files data
%defattr(-,root,root,-)
/usr/share/intel-gpu-tools/1080p-left.png
/usr/share/intel-gpu-tools/1080p-right.png
/usr/share/intel-gpu-tools/README
/usr/share/intel-gpu-tools/fast-feedback.testlist
/usr/share/intel-gpu-tools/meta.testlist
/usr/share/intel-gpu-tools/pass.png
/usr/share/intel-gpu-tools/registers/audio_config_haswell_plus.txt
/usr/share/intel-gpu-tools/registers/audio_debug_haswell_plus.txt
/usr/share/intel-gpu-tools/registers/base_interrupt.txt
/usr/share/intel-gpu-tools/registers/base_other.txt
/usr/share/intel-gpu-tools/registers/base_power.txt
/usr/share/intel-gpu-tools/registers/base_rings.txt
/usr/share/intel-gpu-tools/registers/broadwell
/usr/share/intel-gpu-tools/registers/cherryview
/usr/share/intel-gpu-tools/registers/chv_display_base.txt
/usr/share/intel-gpu-tools/registers/chv_dpio_phy_x1.txt
/usr/share/intel-gpu-tools/registers/chv_dpio_phy_x2.txt
/usr/share/intel-gpu-tools/registers/chv_pipe_b_extra.txt
/usr/share/intel-gpu-tools/registers/chv_pipe_c.txt
/usr/share/intel-gpu-tools/registers/common_display.txt
/usr/share/intel-gpu-tools/registers/gen6_other.txt
/usr/share/intel-gpu-tools/registers/gen7_other.txt
/usr/share/intel-gpu-tools/registers/gen8_interrupt.txt
/usr/share/intel-gpu-tools/registers/gen8_other.txt
/usr/share/intel-gpu-tools/registers/haswell
/usr/share/intel-gpu-tools/registers/haswell_other.txt
/usr/share/intel-gpu-tools/registers/ivybridge
/usr/share/intel-gpu-tools/registers/kabylake
/usr/share/intel-gpu-tools/registers/sandybridge
/usr/share/intel-gpu-tools/registers/skl_display.txt
/usr/share/intel-gpu-tools/registers/skl_powerwells.txt
/usr/share/intel-gpu-tools/registers/skylake
/usr/share/intel-gpu-tools/registers/valleyview
/usr/share/intel-gpu-tools/registers/vlv_cck.txt
/usr/share/intel-gpu-tools/registers/vlv_display_base.txt
/usr/share/intel-gpu-tools/registers/vlv_dpio_phy.txt
/usr/share/intel-gpu-tools/registers/vlv_dsi.txt
/usr/share/intel-gpu-tools/registers/vlv_flisdsi.txt
/usr/share/intel-gpu-tools/registers/vlv_pipe_a.txt
/usr/share/intel-gpu-tools/registers/vlv_pipe_b.txt
/usr/share/intel-gpu-tools/registers/vlv_power.txt

%files dev
%defattr(-,root,root,-)
/usr/lib64/intel_aubdump.so
/usr/lib64/libigt.so
/usr/lib64/pkgconfig/intel-gen4asm.pc
